"use client";

import { ChangeEvent, DragEvent, useEffect, useRef, useState } from "react";
import { AudioLines, ChevronDown, CircleStop, FileAudio, Folder, GripVertical, ImagePlus, LayoutList, ListChecks, ListOrdered, Mic, Pause, Plus, Quote, Search, Sparkles, Table2, Type } from "lucide-react";

type Segment = { start: number; end: number; speaker: string; text: string };
type NoteItem = { id: string; title: string; editedAt: string };
type Tab = "notes" | "transcript" | "summary";
type Menu = "none" | "insert" | "block" | "image";
const fmt = (n: number) => `${Math.floor(n / 60).toString().padStart(2, "0")}:${Math.floor(n % 60).toString().padStart(2, "0")}`;

export default function Home() {
  const editor = useRef<HTMLDivElement>(null), selection = useRef<Range | null>(null), imageInput = useRef<HTMLInputElement>(null);
  const recorder = useRef<MediaRecorder | null>(null), stream = useRef<MediaStream | null>(null), context = useRef<AudioContext | null>(null), frame = useRef<number | null>(null), chunks = useRef<Blob[]>([]), images = useRef(new Map<string, File>());
  const [tab, setTab] = useState<Tab>("notes"), [title, setTitle] = useState("未命名筆記"), [emoji, setEmoji] = useState("📄"), [edited, setEdited] = useState(new Date());
  const [notes, setNotes] = useState<NoteItem[]>([{ id: "first-note", title: "未命名筆記", editedAt: new Date().toISOString() }]), [activeNoteId, setActiveNoteId] = useState("first-note");
  const [recording, setRecording] = useState(false), [paused, setPaused] = useState(false), [seconds, setSeconds] = useState(0), [levels, setLevels] = useState<number[]>(Array(34).fill(6)), [audio, setAudio] = useState<{ blob: Blob; url: string } | null>(null);
  const [segments, setSegments] = useState<Segment[]>([]), [summary, setSummary] = useState(""), [menu, setMenu] = useState<Menu>("none"), [menuAt, setMenuAt] = useState({ x: 150, y: 180 }), [selectedImage, setSelectedImage] = useState<string | null>(null);
  const [transcribing, setTranscribing] = useState(false), [generating, setGenerating] = useState(false), [ocr, setOcr] = useState(false), [draggingImage, setDraggingImage] = useState(false), [error, setError] = useState(""), [status, setStatus] = useState("可直接寫筆記；需要時再開始錄音。");

  useEffect(() => { if (!recording || paused) return; const id = setInterval(() => setSeconds((v) => v + 1), 1000); return () => clearInterval(id); }, [recording, paused]);
  useEffect(() => { const stored = window.localStorage.getItem("memo-ai-notes"); if (!stored) return; try { const saved = JSON.parse(stored) as NoteItem[]; if (saved.length) { setNotes(saved); setActiveNoteId(saved[0].id); setTitle(saved[0].title); } } catch { /* ignore invalid local data */ } }, []);
  useEffect(() => { window.localStorage.setItem("memo-ai-notes", JSON.stringify(notes)); }, [notes]);
  useEffect(() => { const close = () => setMenu("none"); document.addEventListener("mousedown", close); window.addEventListener("scroll", close, true); return () => { document.removeEventListener("mousedown", close); window.removeEventListener("scroll", close, true); }; }, []);
  useEffect(() => { editor.current?.querySelectorAll<HTMLElement>("figure[data-image-id]").forEach((figure) => figure.classList.toggle("memo-image-selected", figure.dataset.imageId === selectedImage)); }, [selectedImage, ocr]);
  useEffect(() => () => { stream.current?.getTracks().forEach((x) => x.stop()); if (frame.current) cancelAnimationFrame(frame.current); void context.current?.close(); if (audio) URL.revokeObjectURL(audio.url); }, [audio]);

  const remember = () => { const s = window.getSelection(); if (s?.rangeCount && editor.current?.contains(s.anchorNode)) selection.current = s.getRangeAt(0).cloneRange(); };
  const renameNote = (value: string) => { setTitle(value); const now = new Date(); setEdited(now); setNotes((current) => current.map((note) => note.id === activeNoteId ? { ...note, title: value || "未命名筆記", editedAt: now.toISOString() } : note)); };
  const newNote = () => { const now = new Date(); const note = { id: crypto.randomUUID(), title: "未命名筆記", editedAt: now.toISOString() }; setNotes((current) => [note, ...current]); setActiveNoteId(note.id); setTitle(note.title); setEdited(now); setSegments([]); setSummary(""); setAudio(null); setSeconds(0); setTab("notes"); if (editor.current) editor.current.innerHTML = ""; setStatus("可直接寫筆記；需要時再開始錄音。"); };
  const selectNote = (note: NoteItem) => { setActiveNoteId(note.id); setTitle(note.title); setEdited(new Date(note.editedAt)); };
  const closeAudio = () => { if (frame.current) cancelAnimationFrame(frame.current); stream.current?.getTracks().forEach((x) => x.stop()); void context.current?.close(); context.current = null; setLevels(Array(34).fill(6)); };
  const insert = (html: string) => { const s = window.getSelection(); editor.current?.focus(); if (selection.current && s) { s.removeAllRanges(); s.addRange(selection.current); } document.execCommand("insertHTML", false, html); setMenu("none"); setEdited(new Date()); };
  const table = () => insert('<table><tbody><tr><th>欄位一</th><th>欄位二</th><th>欄位三</th></tr><tr><td>內容</td><td>內容</td><td>內容</td></tr><tr><td>內容</td><td>內容</td><td>內容</td></tr></tbody></table><p><br></p>');
  const showMenu = (kind: Menu, x?: number, y?: number) => { remember(); const r = selection.current?.getBoundingClientRect(); setMenuAt({ x: x ?? r?.left ?? 160, y: y ?? r?.bottom ?? 230 }); setMenu(kind); };

  const start = async () => {
    setError("");
    try {
      const source = await navigator.mediaDevices.getUserMedia({ audio: { echoCancellation: true, noiseSuppression: true } });
      const mime = MediaRecorder.isTypeSupported("audio/webm;codecs=opus") ? "audio/webm;codecs=opus" : undefined;
      const media = new MediaRecorder(source, mime ? { mimeType: mime } : undefined); chunks.current = [];
      media.ondataavailable = ({ data }) => { if (data.size) chunks.current.push(data); };
      media.onstop = () => { const blob = new Blob(chunks.current, { type: media.mimeType || "audio/webm" }); setAudio({ blob, url: URL.createObjectURL(blob) }); closeAudio(); setStatus("錄音已儲存。下一步可產生逐字稿。 "); };
      const ac = new AudioContext(), analyser = ac.createAnalyser(); analyser.fftSize = 256; ac.createMediaStreamSource(source).connect(analyser); const data = new Uint8Array(analyser.frequencyBinCount);
      const draw = () => { analyser.getByteFrequencyData(data); setLevels(Array.from({ length: 34 }, (_, i) => Math.max(5, Math.min(44, data[Math.floor(i * data.length / 34)] / 5)))); frame.current = requestAnimationFrame(draw); };
      stream.current = source; context.current = ac; recorder.current = media; media.start(1000); void ac.resume(); draw(); setSeconds(0); setSegments([]); setSummary(""); setRecording(true); setPaused(false); setStatus("錄音中；可切換筆記分頁同步記錄。");
    } catch { setError("無法使用麥克風，請在瀏覽器網站權限中允許麥克風。 "); }
  };
  const pause = () => { const media = recorder.current; if (!media) return; if (media.state === "recording") { media.pause(); setPaused(true); } else { media.resume(); setPaused(false); } };
  const stop = () => { const media = recorder.current; if (media && media.state !== "inactive") media.stop(); setRecording(false); setPaused(false); };
  const transcribe = async () => { if (!audio) return; setTranscribing(true); setError(""); try { const body = new FormData(); body.append("audio", new File([audio.blob], "memo-recording.webm", { type: audio.blob.type || "audio/webm" })); const res = await fetch("/api/transcribe", { method: "POST", body }); const data = await res.json() as { error?: string; transcript?: Segment[] }; if (!res.ok) throw new Error(data.error || "轉錄失敗"); setSegments(data.transcript || []); setTab("transcript"); setStatus(data.transcript?.length ? "逐字稿完成，請確認後生成會議總結。" : "沒有辨識到語音內容。"); } catch (e) { setError(e instanceof Error ? e.message : "轉錄失敗。 "); } finally { setTranscribing(false); } };
  const summarize = async () => { if (!segments.length) return; setGenerating(true); setError(""); try { const transcript = segments.map((x) => `[${fmt(x.start)}] ${x.speaker}：${x.text}`).join("\n"); const res = await fetch("/api/ai-notes", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ transcript }) }); const data = await res.json() as { error?: string; notes?: string; empty?: boolean }; if (!res.ok) throw new Error(data.error || "AI 生成失敗。"); setSummary(data.empty ? "" : data.notes || ""); setTab("summary"); setStatus(data.empty ? "逐字稿沒有足夠的會議重點可整理。" : "AI 已依據逐字稿生成會議總結。 "); } catch (e) { setError(e instanceof Error ? e.message : "AI 生成失敗。 "); } finally { setGenerating(false); } };

  const addImage = async (file: File, range?: Range | null) => { if (!file.type.startsWith("image/") && !/\.hei[cf]$/i.test(file.name)) return setError("請上傳圖片檔。 "); const id = crypto.randomUUID(); images.current.set(id, file); let url = URL.createObjectURL(file); if (/\.hei[cf]$/i.test(file.name) || file.type === "image/heic") try { const body = new FormData(); body.append("image", file); const res = await fetch("/api/image-preview", { method: "POST", body }); const data = await res.json() as { dataUrl?: string }; if (data.dataUrl) url = data.dataUrl; } catch { setStatus("HEIC 圖片無法預覽時，仍可右鍵執行文字辨識。 "); } const html = `<figure data-image-id="${id}" contenteditable="false" style="margin:16px 0"><img src="${url}" alt="${file.name}" style="display:block;max-width:100%;max-height:680px;border-radius:8px;cursor:context-menu" /><figcaption style="margin-top:6px;color:#999;font-size:12px">${file.name}</figcaption></figure><p><br></p>`; if (range) { const holder = document.createElement("div"); holder.innerHTML = html; range.deleteContents(); range.insertNode(holder); } else insert(html); setEdited(new Date()); };
  const choose = (e: ChangeEvent<HTMLInputElement>) => { const file = e.target.files?.[0]; if (file) void addImage(file); e.target.value = ""; };
  const drop = (e: DragEvent<HTMLElement>) => { e.preventDefault(); const file = Array.from(e.dataTransfer.files).find((x) => x.type.startsWith("image/") || /\.hei[cf]$/i.test(x.name)); if (!file) return; const doc = document as Document & { caretRangeFromPoint?: (x: number, y: number) => Range }; void addImage(file, doc.caretRangeFromPoint?.(e.clientX, e.clientY) || selection.current); };
  const extract = async () => { if (!selectedImage) return; const file = images.current.get(selectedImage); if (!file) return; setOcr(true); setMenu("none"); setError(""); try { const body = new FormData(); body.append("image", file); const res = await fetch("/api/ocr", { method: "POST", body }); const data = await res.json() as { error?: string; text?: string }; if (!res.ok || !data.text) throw new Error(data.error || "圖片文字辨識失敗"); const figure = editor.current?.querySelector(`figure[data-image-id="${selectedImage}"]`); if (figure) figure.outerHTML = htmlFromText(data.text); setStatus("圖片已轉換為可編輯文字。 "); setEdited(new Date()); } catch (e) { setError(e instanceof Error ? e.message : "圖片文字辨識失敗。 "); } finally { setOcr(false); setSelectedImage(null); } };

  return <main className="flex min-h-screen bg-white text-[#2f2f2f]" onDragOver={(e) => e.preventDefault()}><Sidebar notes={notes} activeNoteId={activeNoteId} onNew={newNote} onSelect={selectNote} /><section className="min-w-0 flex-1 overflow-auto"><header className="flex h-14 items-center border-b border-[#ebebe6] px-6 text-sm text-[#73736d]">所有頁面 <span className="mx-2">/</span> {title}</header><div className="mx-auto max-w-4xl px-10 py-9"><div className="flex items-center gap-3"><input value={emoji} onChange={(e) => setEmoji(e.target.value)} className="h-12 w-14 border-0 bg-transparent text-center text-3xl outline-none" title="點擊後按 Control + Command + Space 開啟系統 Emoji 選擇器" /><span className="text-xs text-[#999]">點擊圖示後按 ⌃⌘Space 使用系統 Emoji</span></div><input value={title} onChange={(e) => renameNote(e.target.value)} className="mt-3 w-full border-0 bg-transparent text-4xl font-bold outline-none" /><p className="mt-2 text-sm text-[#999]">上次編輯：{edited.toLocaleString("zh-TW", { month: "long", day: "numeric", hour: "2-digit", minute: "2-digit" })} · 私人頁面</p>
      <Recorder recording={recording} paused={paused} audio={audio} seconds={seconds} levels={levels} transcribing={transcribing} status={status} onStart={start} onPause={pause} onStop={stop} onTranscribe={transcribe} />
      <nav className="mt-7 flex items-center gap-1 border-b border-[#e9e9e4]"><Tab active={tab === "notes"} label="筆記" onClick={() => setTab("notes")} /><Tab active={tab === "transcript"} disabled={!segments.length} label={`逐字稿${segments.length ? ` (${segments.length})` : ""}`} onClick={() => setTab("transcript")} /><Tab active={tab === "summary"} disabled={!segments.length} label="AI 總結" onClick={() => setTab("summary")} />{tab === "transcript" && <button disabled={generating} onClick={summarize} className="ml-auto mb-2 rounded-md bg-[#715df2] px-3 py-2 text-sm text-white"><Sparkles className="mr-1 inline h-4 w-4" />{generating ? "生成中…" : "生成會議總結"}</button>}</nav>
      {tab === "notes" && (
        <section className="pt-5" onDragEnter={(event) => { event.preventDefault(); setDraggingImage(true); }} onDragOver={(event) => { event.preventDefault(); setDraggingImage(true); }} onDragLeave={(event) => { if (event.currentTarget === event.target) setDraggingImage(false); }} onDrop={(event) => { setDraggingImage(false); drop(event); }}>
          <Toolbar onImage={() => imageInput.current?.click()} onTable={table} onInsert={insert} />
          <div className="group relative pl-16">
            {draggingImage && <div className="notion-drop-line" aria-label="圖片將插入此處" />}
            <div className="absolute -left-1 top-3 hidden gap-1 group-hover:flex">
              <button onMouseDown={(event) => event.preventDefault()} onClick={() => showMenu("insert")} className="grid h-7 w-7 place-items-center rounded text-[#888] hover:bg-[#f1f1ed]"><Plus className="h-4 w-4" /></button>
              <button onMouseDown={(event) => event.preventDefault()} onClick={() => showMenu("block")} className="grid h-7 w-7 place-items-center rounded text-[#888] hover:bg-[#f1f1ed]"><GripVertical className="h-4 w-4" /></button>
            </div>
            <div ref={editor} contentEditable suppressContentEditableWarning onInput={() => { remember(); setEdited(new Date()); }} onKeyUp={remember} onMouseUp={remember} onKeyDown={(event) => { if (event.key === "/") showMenu("insert"); if (event.key === "Escape") setMenu("none"); }} onContextMenu={(event) => { const figure = (event.target as HTMLElement).closest("figure[data-image-id]"); if (figure) { event.preventDefault(); setSelectedImage(figure.getAttribute("data-image-id")); showMenu("image", event.clientX, event.clientY); } }} className="memo-editor min-h-[360px] py-5 outline-none" data-placeholder="輸入 / 可叫出區塊選單，或拖曳圖片到此處…" />
          </div>
          <input ref={imageInput} type="file" accept="image/*,.heic,.heif" className="hidden" onChange={choose} />
        </section>
      )}
      {tab === "transcript" && <Transcript segments={segments} onChange={(index, text) => { setSegments((current) => current.map((segment, itemIndex) => itemIndex === index ? { ...segment, text } : segment)); setEdited(new Date()); }} />}{tab === "summary" && <Summary value={summary} generating={generating} onChange={(value) => { setSummary(value); setEdited(new Date()); }} onGenerate={summarize} />}{menu !== "none" && <BlockMenu kind={menu} point={menuAt} onInsert={insert} onTable={table} onImage={() => imageInput.current?.click()} onOCR={extract} />}{ocr && <div className="fixed bottom-7 right-7 z-50 rounded-full bg-[#292928] px-4 py-3 text-sm text-white shadow-xl">AI 正在辨識圖片文字…</div>}{error && <p className="mt-4 rounded bg-red-50 p-3 text-sm text-red-700">{error}</p>}</div></section></main>;
}

function Sidebar({ notes, activeNoteId, onNew, onSelect }: { notes: NoteItem[]; activeNoteId: string; onNew: () => void; onSelect: (note: NoteItem) => void }) { return <aside className="sticky top-0 flex h-screen w-64 shrink-0 flex-col border-r border-[#e9e9e4] bg-[#fbfbfa] p-3"><div className="mb-7 flex items-center gap-2 px-2 pt-1 text-lg font-semibold"><span className="grid h-7 w-7 place-items-center rounded-md bg-[#715df2] text-sm text-white">m</span>Memo AI</div><button onClick={onNew} className="mb-3 flex gap-2 rounded-md border border-[#deded8] bg-white px-3 py-2.5 text-sm font-medium text-[#444] shadow-sm hover:bg-[#f5f4ff]"><Plus className="h-4 w-4" />新增筆記</button><button className="flex gap-2 rounded px-2 py-2 text-sm hover:bg-[#efefea]"><LayoutList className="h-4 w-4" />所有筆記</button><button className="flex gap-2 rounded px-2 py-2 text-sm hover:bg-[#efefea]"><Search className="h-4 w-4" />搜尋</button><p className="mt-7 px-2 text-xs text-[#999]">私人資料夾</p><div className="mt-2"><p className="flex gap-2 px-2 text-sm text-[#666]"><Folder className="h-4 w-4" />所有筆記</p><div className="mt-1 space-y-0.5">{notes.map((note) => <button key={note.id} onClick={() => onSelect(note)} className={`w-full truncate rounded px-3 py-2 text-left text-sm ${activeNoteId === note.id ? "bg-[#ece9ff] text-[#604deb]" : "text-[#555] hover:bg-[#efefea]"}`}>{note.title || "未命名筆記"}</button>)}</div></div><div className="mt-auto border-t border-[#e9e9e4] px-2 py-3 text-sm text-[#73736d]">Jay Lin <ChevronDown className="float-right h-4 w-4" /></div></aside>; }
function Recorder({ recording, paused, audio, seconds, levels, transcribing, status, onStart, onPause, onStop, onTranscribe }: { recording: boolean; paused: boolean; audio: { blob: Blob; url: string } | null; seconds: number; levels: number[]; transcribing: boolean; status: string; onStart: () => void; onPause: () => void; onStop: () => void; onTranscribe: () => void }) { return <section className="mt-7 rounded-lg border border-[#e8e8e3]"><div className="flex items-center gap-2 border-b border-[#eee] px-4 py-3"><AudioLines className="h-4 w-4 text-[#715df2]" /><b className="text-sm">會議錄音</b><span className="rounded-full bg-[#f3f3ef] px-2 py-1 text-xs">{recording ? (paused ? "已暫停" : "錄音中") : audio ? "已儲存" : "尚未開始"}</span><span className="ml-auto font-mono">{fmt(seconds)}</span></div><div className="px-4 py-3"><p className="text-sm text-[#74746f]">{status}</p>{recording && <div className="mt-3 flex h-9 items-center gap-1 rounded bg-[#fafaf8] px-3">{levels.map((v, i) => <span key={i} className="w-1 flex-1 rounded-full bg-[#917fff]" style={{ height: `${v}px` }} />)}</div>}<div className="mt-3 flex flex-wrap gap-2">{!recording && !audio && <button onClick={onStart} className="rounded-md bg-[#2f2f2f] px-3 py-2 text-sm text-white"><Mic className="mr-1 inline h-4 w-4" />開始錄音</button>}{recording && <><button onClick={onPause} className="rounded-md border px-3 py-2 text-sm"><Pause className="mr-1 inline h-4 w-4" />{paused ? "繼續" : "暫停"}</button><button onClick={onStop} className="rounded-md bg-red-50 px-3 py-2 text-sm text-red-700"><CircleStop className="mr-1 inline h-4 w-4" />停止並儲存</button></>}{audio && !recording && <button disabled={transcribing} onClick={onTranscribe} className="rounded-md border border-[#715df2] px-3 py-2 text-sm text-[#604deb]"><FileAudio className="mr-1 inline h-4 w-4" />{transcribing ? "轉錄中…" : "產生逐字稿"}</button>}</div>{audio && <audio className="mt-3 h-9 w-full" controls src={audio.url} />}</div></section>; }
function Tab({ active, disabled, label, onClick }: { active: boolean; disabled?: boolean; label: string; onClick: () => void }) { return <button disabled={disabled} onClick={onClick} className={`border-b-2 px-3 py-2 text-sm ${active ? "border-[#715df2] text-[#604deb]" : "border-transparent text-[#777]"} disabled:opacity-40`}>{label}</button>; }
function Toolbar({ onImage, onTable, onInsert }: { onImage: () => void; onTable: () => void; onInsert: (html: string) => void }) { return <div className="mb-2 flex flex-wrap gap-2"><div className="flex rounded-md border border-[#e5e5df] bg-[#fafaf9] p-1">{[["H1", "<h1>標題</h1><p><br></p>"], ["H2", "<h2>小標題</h2><p><br></p>"], ["待辦", "<p>☐ 待辦事項</p>"], ["引用", "<blockquote>引用內容</blockquote><p><br></p>"]].map(([label, html]) => <button key={label} onClick={() => onInsert(html)} className="px-2 py-1 text-xs">{label}</button>)}<button onClick={onTable} className="px-2 py-1 text-xs">表格</button></div><button onMouseDown={(e) => e.preventDefault()} onClick={onImage} className="rounded-md border border-[#e5e5df] px-2.5 py-1.5 text-xs"><ImagePlus className="mr-1 inline h-3.5 w-3.5" />圖片</button></div>; }
function Transcript({ segments, onChange }: { segments: Segment[]; onChange: (index: number, text: string) => void }) { return <section className="py-6"><div className="mb-4 flex items-end justify-between"><h2 className="text-xl font-semibold">逐字稿</h2><p className="text-xs text-[#999]">可直接修改內容；變更後會用於下一次 AI 總結。</p></div><div className="space-y-3">{segments.map((item, i) => <article key={`${item.start}-${i}`} className="flex gap-4 rounded-lg bg-[#fafaf9] p-4"><span className="font-mono text-sm text-[#715df2]">{fmt(item.start)}</span><div className="min-w-0 flex-1"><b className="text-sm">{item.speaker}</b><textarea value={item.text} onChange={(event) => onChange(i, event.target.value)} className="mt-1 min-h-16 w-full resize-y bg-transparent leading-7 text-[#555] outline-none" aria-label={`${item.speaker} 的逐字稿`} /></div></article>)}</div></section>; }
function Summary({ value, generating, onChange, onGenerate }: { value: string; generating: boolean; onChange: (value: string) => void; onGenerate: () => void }) { return <section className="py-6"><div className="mb-4 flex justify-between"><h2 className="text-xl font-semibold">會議總結</h2><button disabled={generating} onClick={onGenerate} className="rounded-md bg-[#715df2] px-3 py-2 text-sm text-white"><Sparkles className="mr-1 inline h-4 w-4" />{generating ? "生成中…" : "重新生成"}</button></div>{value ? <textarea value={value} onChange={(e) => onChange(e.target.value)} className="min-h-[480px] w-full resize-y border-0 leading-7 outline-none" /> : <div className="grid min-h-[360px] place-items-center text-center"><div><Sparkles className="mx-auto mb-3 h-6 w-6 text-[#a99cff]" /><h3 className="font-medium">目前沒有可整理的會議重點</h3><p className="mt-2 max-w-sm text-sm leading-6 text-[#888]">AI 只會呈現逐字稿實際提及的內容；當內容不足或沒有重點時，會保留空白而不補上制式模板。</p></div></div>}</section>; }
function BlockMenu({ kind, point, onInsert, onTable, onImage, onOCR }: { kind: Menu; point: { x: number; y: number }; onInsert: (html: string) => void; onTable: () => void; onImage: () => void; onOCR: () => void }) { const item = (label: string, click: () => void) => <button key={label} onClick={click} className="block w-full rounded px-2 py-2 text-left text-sm hover:bg-[#f4f3ff]">{label}</button>; return <div onMouseDown={(e) => e.stopPropagation()} style={{ left: point.x, top: point.y }} className="fixed z-50 w-56 rounded-lg border border-[#deded8] bg-white p-2 shadow-xl">{kind === "insert" && <><p className="px-2 text-xs text-[#888]">新增區塊</p>{item("文字", () => onInsert("<p>文字</p>"))}{item("待辦清單", () => onInsert("<p>☐ 待辦事項</p>"))}{item("引用", () => onInsert("<blockquote>引用內容</blockquote>"))}{item("表格", onTable)}{item("圖片", onImage)}</>}{kind === "block" && <><p className="px-2 text-xs text-[#888]">區塊操作</p>{item("轉換為標題", () => document.execCommand("formatBlock", false, "h2"))}{item("轉換為待辦", () => onInsert("<p>☐ 待辦事項</p>"))}{item("複製目前區塊", () => document.execCommand("copy"))}</>}{kind === "image" && item("✨ AI 轉換為文字", onOCR)}</div>; }
function htmlFromText(text: string) { const esc = (v: string) => v.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;"); const out: string[] = []; let list = ""; const close = () => { if (list) out.push(`</${list}>`); list = ""; }; for (const raw of text.split("\n")) { const line = raw.trim(); if (!line) { close(); continue; } const bullet = /^[-•●]\s+(.+)/.exec(line), order = /^\d+[.)、]\s+(.+)/.exec(line); if (bullet || order) { const tag = bullet ? "ul" : "ol"; if (list !== tag) { close(); list = tag; out.push(`<${tag}>`); } out.push(`<li>${esc((bullet || order)![1])}</li>`); } else { close(); if (/^#{1,3}\s/.test(line)) { const level = Math.min(3, line.match(/^#+/)![0].length); out.push(`<h${level}>${esc(line.replace(/^#+\s*/, ""))}</h${level}>`); } else if (line.length < 32 && !/[，。；：,.]/.test(line)) out.push(`<h2>${esc(line)}</h2>`); else out.push(`<p>${esc(line)}</p>`); } } close(); return out.join(""); }
